
services:
  starships-app:
    build:
      context: ./starships-app
    ports:
      - "8000:8000"
    environment:
      CHALICE_LOCAL: "true"

  starship-frontend:
    build:
      context: ./starship-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    depends_on:
      - starships-app
      - bff

  bff:
    build:
      context: ./bff
    ports:
      - "5000:5000"
    depends_on:
      - starships-app
    environment:
      - DOCKER_COMPOSE=true