# .github/workflows/app.yaml
name: python pytest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starships-app
    timeout-minutes: 5
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pip
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          

      - run: pytest
      